# Generated by Django 3.2.4 on 2021-06-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Super_AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(default='First Name', max_length=255)),
                ('Profile', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='SuperAdmin/')),
            ],
        ),
    ]
